version: '3.1'
services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: schoolsTest
      MYSQL_DATABASE: schoolsdb
  proxy:
    build: ./proxy
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "~/certs/:/etc/letsencrypt/:ro"
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host:192.168.0.11"
